// This file was generated by the "svnrev" utility
// You should not modify it manually, as it may be re-generated.
//
// $Revision: 2872 $
// $Date: 2011-7-20 $
//

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("SeeMS")]
[assembly: AssemblyDescription("A visualization, annotation, and processing tool for mass spectrometry data.")]
[assembly: AssemblyCompany("Vanderbilt University")]
[assembly: AssemblyProduct("SeeMS")]
[assembly: AssemblyCopyright("Copyright © Vanderbilt University 2011")]
[assembly: AssemblyVersion("2.2.2872")]
[assembly: AssemblyFileVersion("2.2.2872")]
